# Generated by Django 3.2.15 on 2022-08-22 12:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ratings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='rating',
            name='score',
            field=models.PositiveSmallIntegerField(choices=[(5, 'excellence'), (4, 'very good'), (3, 'good'), (2, 'poor'), (1, 'bad')], default=0),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('owner', 'product')},
        ),
    ]
