# Generated by Django 3.2.15 on 2022-08-20 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.IntegerField(choices=[(0, 'Boards'), (1, 'Kites'), (2, 'Wetsuits'), (3, 'Harnesses'), (4, 'Others')])),
                ('price_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR'), ('USD', 'USD'), ('GBP', 'GBP'), ('PLN', 'PLN')], default=None, editable=False, max_length=3, null=True)),
                ('price', djmoney.models.fields.MoneyField(currency_choices=(('EUR', 'EUR'), ('USD', 'USD'), ('GBP', 'GBP'), ('PLN', 'PLN')), decimal_places=2, max_digits=10, null=True)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=500)),
                ('brand', models.CharField(max_length=50)),
                ('inStock', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='../default-image_aqtoyb', upload_to='images/')),
                ('product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='products.product')),
            ],
        ),
    ]
