# Generated by Django 3.2.15 on 2022-08-26 17:16

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20220826_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=djmoney.models.fields.MoneyField(currency_choices=(('EUR', 'EUR'), ('USD', 'USD'), ('GBP', 'GBP'), ('PLN', 'PLN')), decimal_places=2, default_currency='EUR', max_digits=10),
        ),
    ]
