# Generated by Django 3.2.15 on 2022-09-12 15:45

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_rename_address_product_street'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=djmoney.models.fields.MoneyField(currency_choices=(('EUR', '€'), ('USD', '$'), ('GBP', '£'), ('PLN', 'zł')), decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('EUR', '€'), ('USD', '$'), ('GBP', '£'), ('PLN', 'zł')], default=None, editable=False, max_length=3),
        ),
    ]
