# Generated by Django 3.2.15 on 2022-09-15 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0018_auto_20220912_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='owner',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='profiles.user'),
            preserve_default=False,
        ),
    ]
