# Generated by Django 3.2.15 on 2022-09-20 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_alter_product_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='product',
            name='city',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='street',
            field=models.CharField(max_length=50),
        ),
    ]
